name: Build Android Debug APK

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.13.1'  # Cambia esto según la versión de Node.js que necesites

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install  --legacy-peer-deps

      - name: Build Android Debug APK
        run: |
          ionic capacitor build android

      - name: Check data
        run: |
          cd android
          ./gradlew assembleDebug
      


